//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("UniblueLabsModel", "FK_Projects_Developers", "Developers", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WPFDisciples.Backend.Developers), "Projects", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WPFDisciples.Backend.Projects))]

// Original file name:
// Generation date: 3/26/2009 4:45:12 PM
namespace WPFDisciples.Backend
{

    /// <summary>
    /// There are no comments for UniblueLabsEntities in the schema.
    /// </summary>
    public partial class UniblueLabsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new UniblueLabsEntities object using the connection string found in the 'UniblueLabsEntities' section of the application configuration file.
        /// </summary>
        public UniblueLabsEntities() :
            base("name=UniblueLabsEntities", "UniblueLabsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new UniblueLabsEntities object.
        /// </summary>
        public UniblueLabsEntities(string connectionString) :
            base(connectionString, "UniblueLabsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new UniblueLabsEntities object.
        /// </summary>
        public UniblueLabsEntities(global::System.Data.EntityClient.EntityConnection connection) :
            base(connection, "UniblueLabsEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Developers in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Developers> Developers
        {
            get
            {
                if ((this._Developers == null))
                {
                    this._Developers = base.CreateQuery<Developers>("[Developers]");
                }
                return this._Developers;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Developers> _Developers;
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Projects> Projects
        {
            get
            {
                if ((this._Projects == null))
                {
                    this._Projects = base.CreateQuery<Projects>("[Projects]");
                }
                return this._Projects;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Projects> _Projects;
        /// <summary>
        /// There are no comments for Developers in the schema.
        /// </summary>
        public void AddToDevelopers(Developers developers)
        {
            base.AddObject("Developers", developers);
        }
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        public void AddToProjects(Projects projects)
        {
            base.AddObject("Projects", projects);
        }
    }
    /// <summary>
    /// There are no comments for UniblueLabsModel.Developers in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName = "UniblueLabsModel", Name = "Developers")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference = true)]
    [global::System.Serializable()]
    public partial class Developers : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Developers object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        public static Developers CreateDevelopers(int id)
        {
            Developers developers = new Developers();
            developers.id = id;
            return developers;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Avatar in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Avatar
        {
            get
            {
                return this._Avatar;
            }
            set
            {
                this.OnAvatarChanging(value);
                this.ReportPropertyChanging("Avatar");
                this._Avatar = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Avatar");
                this.OnAvatarChanged();
            }
        }
        private string _Avatar;
        partial void OnAvatarChanging(string value);
        partial void OnAvatarChanged();
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("UniblueLabsModel", "FK_Projects_Developers", "Projects")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Projects> Projects
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Projects>("UniblueLabsModel.FK_Projects_Developers", "Projects");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Projects>("UniblueLabsModel.FK_Projects_Developers", "Projects", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for UniblueLabsModel.Projects in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName = "UniblueLabsModel", Name = "Projects")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference = true)]
    [global::System.Serializable()]
    public partial class Projects : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Projects object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        public static Projects CreateProjects(int id)
        {
            Projects projects = new Projects();
            projects.id = id;
            return projects;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Link in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Link
        {
            get
            {
                return this._Link;
            }
            set
            {
                this.OnLinkChanging(value);
                this.ReportPropertyChanging("Link");
                this._Link = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Link");
                this.OnLinkChanged();
            }
        }
        private string _Link;
        partial void OnLinkChanging(string value);
        partial void OnLinkChanged();
        /// <summary>
        /// There are no comments for Developers in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("UniblueLabsModel", "FK_Projects_Developers", "Developers")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Developers Developers
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Developers>("UniblueLabsModel.FK_Projects_Developers", "Developers").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Developers>("UniblueLabsModel.FK_Projects_Developers", "Developers").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Developers in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Developers> DevelopersReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Developers>("UniblueLabsModel.FK_Projects_Developers", "Developers");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Developers>("UniblueLabsModel.FK_Projects_Developers", "Developers", value);
                }
            }
        }
    }
}
