//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecuredWpfApplication.SecuredService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorDetails", Namespace="http://schemas.datacontract.org/2004/07/SecuredWcfService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecuredWpfApplication.SecuredService.ApplicationErrorDetails))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecuredWpfApplication.SecuredService.DatabaseOfflineErrorDetails))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecuredWpfApplication.SecuredService.DatabaseProcessingErrorDetails))]
    public partial class ErrorDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateTimeField, value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName {
            get {
                return this.MethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodNameField, value) != true)) {
                    this.MethodNameField = value;
                    this.RaisePropertyChanged("MethodName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationErrorDetails", Namespace="http://schemas.datacontract.org/2004/07/SecuredWcfService")]
    [System.SerializableAttribute()]
    public partial class ApplicationErrorDetails : SecuredWpfApplication.SecuredService.ErrorDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseOfflineErrorDetails", Namespace="http://schemas.datacontract.org/2004/07/SecuredWcfService")]
    [System.SerializableAttribute()]
    public partial class DatabaseOfflineErrorDetails : SecuredWpfApplication.SecuredService.ErrorDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseProcessingErrorDetails", Namespace="http://schemas.datacontract.org/2004/07/SecuredWcfService")]
    [System.SerializableAttribute()]
    public partial class DatabaseProcessingErrorDetails : SecuredWpfApplication.SecuredService.ErrorDetails {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecuredService.ISecuredService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ISecuredService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecuredService/Login", ReplyAction="http://tempuri.org/ISecuredService/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecuredWpfApplication.SecuredService.ErrorDetails), Action="http://tempuri.org/ISecuredService/LoginErrorDetailsFault", Name="ErrorDetails", Namespace="http://schemas.datacontract.org/2004/07/SecuredWcfService")]
        bool Login(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecuredService/GetLoggedInUser", ReplyAction="http://tempuri.org/ISecuredService/GetLoggedInUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecuredWpfApplication.SecuredService.ErrorDetails), Action="http://tempuri.org/ISecuredService/GetLoggedInUserErrorDetailsFault", Name="ErrorDetails", Namespace="http://schemas.datacontract.org/2004/07/SecuredWcfService")]
        string GetLoggedInUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecuredService/IsLoggedIn", ReplyAction="http://tempuri.org/ISecuredService/IsLoggedInResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecuredWpfApplication.SecuredService.ErrorDetails), Action="http://tempuri.org/ISecuredService/IsLoggedInErrorDetailsFault", Name="ErrorDetails", Namespace="http://schemas.datacontract.org/2004/07/SecuredWcfService")]
        bool IsLoggedIn();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecuredServiceChannel : SecuredWpfApplication.SecuredService.ISecuredService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecuredServiceClient : System.ServiceModel.ClientBase<SecuredWpfApplication.SecuredService.ISecuredService>, SecuredWpfApplication.SecuredService.ISecuredService {
        
        public SecuredServiceClient() {
        }
        
        public SecuredServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecuredServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuredServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuredServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string Username, string Password) {
            return base.Channel.Login(Username, Password);
        }
        
        public string GetLoggedInUser() {
            return base.Channel.GetLoggedInUser();
        }
        
        public bool IsLoggedIn() {
            return base.Channel.IsLoggedIn();
        }
    }
}
