//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.FantasyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FantasyService.IFantasyService")]
    public interface IFantasyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFantasyService/GetLeagueNames", ReplyAction="http://tempuri.org/IFantasyService/GetLeagueNamesResponse")]
        string[] GetLeagueNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFantasyService/GetTeamWins", ReplyAction="http://tempuri.org/IFantasyService/GetTeamWinsResponse")]
        int GetTeamWins(int teamId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFantasyServiceChannel : ConsoleClient.FantasyService.IFantasyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FantasyServiceClient : System.ServiceModel.ClientBase<ConsoleClient.FantasyService.IFantasyService>, ConsoleClient.FantasyService.IFantasyService {
        
        public FantasyServiceClient() {
        }
        
        public FantasyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FantasyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FantasyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FantasyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetLeagueNames() {
            return base.Channel.GetLeagueNames();
        }
        
        public int GetTeamWins(int teamId) {
            return base.Channel.GetTeamWins(teamId);
        }
    }
}
