<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" name="SecuredApplicationServiceShell2" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsp:Policy wsu:Id="SecuredApplicationServiceShell2Endpoint_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:TransportToken>
              <wsp:Policy>
                <sp:HttpsToken RequireClientCertificate="false" />
              </wsp:Policy>
            </sp:TransportToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256 />
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict />
              </wsp:Policy>
            </sp:Layout>
            <sp:IncludeTimestamp />
          </wsp:Policy>
        </sp:TransportBinding>
        <sp:EndorsingSupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:X509Token sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
              <wsp:Policy>
                <sp:RequireThumbprintReference />
                <sp:WssX509V3Token10 />
              </wsp:Policy>
            </sp:X509Token>
            <sp:SignedParts>
              <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
            </sp:SignedParts>
          </wsp:Policy>
        </sp:EndorsingSupportingTokens>
        <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:MustSupportRefThumbprint />
          </wsp:Policy>
        </sp:Wss11>
        <sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:MustSupportIssuedTokens />
            <sp:RequireClientEntropy />
            <sp:RequireServerEntropy />
          </wsp:Policy>
        </sp:Trust10>
        <wsaw:UsingAddressing />
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <xsd:import namespace="http://schemas.datacontract.org/2004/07/IdentityStream.Models" />
      <xsd:import namespace="http://schemas.datacontract.org/2004/07/IdentityStream.Server.Data" />
      <xsd:element name="GetCountries">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs="0" name="requestData" nillable="true" xmlns:q1="http://schemas.datacontract.org/2004/07/IdentityStream.Models" type="q1:RequestData" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="GetCountriesResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs="0" name="GetCountriesResult" nillable="true" xmlns:q2="http://schemas.datacontract.org/2004/07/IdentityStream.Server.Data" type="q2:ArrayOfCountryData" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
    <xsd:schema xmlns:tns="http://schemas.datacontract.org/2004/07/IdentityStream.Models" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/IdentityStream.Models">
      <xsd:import namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
      <xsd:complexType name="RequestData">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="IdentityUid" type="ser:guid" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:element name="RequestData" nillable="true" type="tns:RequestData" />
    </xsd:schema>
    <xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="anyType" nillable="true" type="xs:anyType" />
      <xs:element name="anyURI" nillable="true" type="xs:anyURI" />
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
      <xs:element name="boolean" nillable="true" type="xs:boolean" />
      <xs:element name="byte" nillable="true" type="xs:byte" />
      <xs:element name="dateTime" nillable="true" type="xs:dateTime" />
      <xs:element name="decimal" nillable="true" type="xs:decimal" />
      <xs:element name="double" nillable="true" type="xs:double" />
      <xs:element name="float" nillable="true" type="xs:float" />
      <xs:element name="int" nillable="true" type="xs:int" />
      <xs:element name="long" nillable="true" type="xs:long" />
      <xs:element name="QName" nillable="true" type="xs:QName" />
      <xs:element name="short" nillable="true" type="xs:short" />
      <xs:element name="string" nillable="true" type="xs:string" />
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort" />
      <xs:element name="char" nillable="true" type="tns:char" />
      <xs:simpleType name="char">
        <xs:restriction base="xs:int" />
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration" />
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid" />
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName" />
      <xs:attribute name="Id" type="xs:ID" />
      <xs:attribute name="Ref" type="xs:IDREF" />
    </xs:schema>
    <xsd:schema xmlns:tns="http://schemas.datacontract.org/2004/07/IdentityStream.Server.Data" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/IdentityStream.Server.Data">
      <xsd:complexType name="ArrayOfCountryData">
        <xsd:sequence>
          <xsd:element minOccurs="0" maxOccurs="unbounded" name="CountryData" nillable="true" type="tns:CountryData" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:element name="ArrayOfCountryData" nillable="true" type="tns:ArrayOfCountryData" />
      <xsd:complexType name="CountryData">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="Code" nillable="true" type="xsd:string" />
          <xsd:element minOccurs="0" name="Description" nillable="true" type="xsd:string" />
          <xsd:element minOccurs="0" name="Enabled" type="xsd:int" />
          <xsd:element minOccurs="0" name="Id" type="xsd:int" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:element name="CountryData" nillable="true" type="tns:CountryData" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ISecuredApplicationService_GetCountries_InputMessage">
    <wsdl:part name="parameters" element="tns:GetCountries" />
  </wsdl:message>
  <wsdl:message name="ISecuredApplicationService_GetCountries_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetCountriesResponse" />
  </wsdl:message>
  <wsdl:portType name="ISecuredApplicationService">
    <wsdl:operation name="GetCountries">
      <wsdl:input wsaw:Action="http://tempuri.org/ISecuredApplicationService/GetCountries" message="tns:ISecuredApplicationService_GetCountries_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/ISecuredApplicationService/GetCountriesResponse" message="tns:ISecuredApplicationService_GetCountries_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SecuredApplicationServiceShell2Endpoint" type="tns:ISecuredApplicationService">
    <wsp:PolicyReference URI="#SecuredApplicationServiceShell2Endpoint_policy" />
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetCountries">
      <soap12:operation soapAction="http://tempuri.org/ISecuredApplicationService/GetCountries" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SecuredApplicationServiceShell2">
    <wsdl:port name="SecuredApplicationServiceShell2Endpoint" binding="tns:SecuredApplicationServiceShell2Endpoint">
      <soap12:address location="https://localhost/Service/finder" />
      <wsa10:EndpointReference>
        <wsa10:Address>https://localhost/Service/finder</wsa10:Address>
      </wsa10:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>