//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CdcSoftware.Workflow.Core.Test.Test {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Test.WorkflowRemote")]
    public interface WorkflowRemote {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WorkflowRemote/StartWorkflow", ReplyAction="http://tempuri.org/WorkflowRemote/StartWorkflowResponse")]
        bool StartWorkflow(string MarkupFileName, string RulesFileName, CdcSoftware.Workflow.Core.WorkflowParameters Parameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WorkflowRemoteChannel : CdcSoftware.Workflow.Core.Test.Test.WorkflowRemote, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WorkflowRemoteClient : System.ServiceModel.ClientBase<CdcSoftware.Workflow.Core.Test.Test.WorkflowRemote>, CdcSoftware.Workflow.Core.Test.Test.WorkflowRemote {
        
        public WorkflowRemoteClient() {
        }
        
        public WorkflowRemoteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkflowRemoteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkflowRemoteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkflowRemoteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool StartWorkflow(string MarkupFileName, string RulesFileName, CdcSoftware.Workflow.Core.WorkflowParameters Parameters) {
            return base.Channel.StartWorkflow(MarkupFileName, RulesFileName, Parameters);
        }
    }
}
