'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ErrorDetails", [Namespace]:="http://schemas.datacontract.org/2004/07/IdentityStream.Services.IntegrationServic"& _ 
        "es"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ErrorDetails
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateTimeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExceptionTypeField As ServiceReference1.ServiceException
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MethodNameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateTime() As String
            Get
                Return Me.DateTimeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DateTimeField, value) <> true) Then
                    Me.DateTimeField = value
                    Me.RaisePropertyChanged("DateTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExceptionType() As ServiceReference1.ServiceException
            Get
                Return Me.ExceptionTypeField
            End Get
            Set
                If (Me.ExceptionTypeField.Equals(value) <> true) Then
                    Me.ExceptionTypeField = value
                    Me.RaisePropertyChanged("ExceptionType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MethodName() As String
            Get
                Return Me.MethodNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MethodNameField, value) <> true) Then
                    Me.MethodNameField = value
                    Me.RaisePropertyChanged("MethodName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceException", [Namespace]:="http://schemas.datacontract.org/2004/07/IdentityStream.Services.IntegrationServic"& _ 
        "es")>  _
    Public Enum ServiceException As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DatabaseOffline = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DatabaseProcessingError = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Application = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IIntegrator")>  _
    Public Interface IIntegrator
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIntegrator/ReplaceIdentitySourceId", ReplyAction:="http://tempuri.org/IIntegrator/ReplaceIdentitySourceIdResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReference1.ErrorDetails), Action:="http://tempuri.org/IIntegrator/ReplaceIdentitySourceIdErrorDetailsFault", Name:="ErrorDetails", [Namespace]:="http://schemas.datacontract.org/2004/07/IdentityStream.Services.IntegrationServic"& _ 
            "es")>  _
        Sub ReplaceIdentitySourceId(ByVal oldId As String, ByVal replacementId As String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IIntegratorChannel
        Inherits ServiceReference1.IIntegrator, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class IntegratorClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IIntegrator)
        Implements ServiceReference1.IIntegrator
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub ReplaceIdentitySourceId(ByVal oldId As String, ByVal replacementId As String) Implements ServiceReference1.IIntegrator.ReplaceIdentitySourceId
            MyBase.Channel.ReplaceIdentitySourceId(oldId, replacementId)
        End Sub
    End Class
End Namespace
