//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscortClient.EscortServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EscortServiceReference.IEscortService")]
    public interface IEscortService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEscortService/Escort", ReplyAction="http://tempuri.org/IEscortService/EscortResponse")]
        bool Escort(int quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEscortServiceChannel : EscortClient.EscortServiceReference.IEscortService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EscortServiceClient : System.ServiceModel.ClientBase<EscortClient.EscortServiceReference.IEscortService>, EscortClient.EscortServiceReference.IEscortService {
        
        public EscortServiceClient() {
        }
        
        public EscortServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EscortServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EscortServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EscortServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Escort(int quantity) {
            return base.Channel.Escort(quantity);
        }
    }
}
