//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// CODEGEN: The binding 'NetTcpBinding_ISyncEvents' from #pragma warning disable 1591

namespace 'http://tempuri.org/' was ignored.  There is no SoapTransportImporter that understands the transport 'http://schemas.microsoft.com/soap/tcp'.
// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
namespace ServiceModelEx.localhost {
    
}

#pragma warning restore 1591