//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS_Web_Service_Test.OfsProcessingReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="IdentityStream.T24WebServices", ConfigurationName="OfsProcessingReference.OfsProcessing")]
    public interface OfsProcessing {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        bool TransactionRequest(string String_1, string String_2, string String_3, string String_4);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface OfsProcessingChannel : JMS_Web_Service_Test.OfsProcessingReference.OfsProcessing, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OfsProcessingClient : System.ServiceModel.ClientBase<JMS_Web_Service_Test.OfsProcessingReference.OfsProcessing>, JMS_Web_Service_Test.OfsProcessingReference.OfsProcessing {
        
        public OfsProcessingClient() {
        }
        
        public OfsProcessingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfsProcessingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfsProcessingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfsProcessingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TransactionRequest(string String_1, string String_2, string String_3, string String_4) {
            return base.Channel.TransactionRequest(String_1, String_2, String_3, String_4);
        }
    }
}
