//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.learn2develop.net/", ConfigurationName="ServiceReference1.TicketingService", CallbackContract=typeof(Client.ServiceReference1.TicketingServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface TicketingService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.learn2develop.net/TicketingService/SetSeatStatus")]
        void SetSeatStatus(string strSeats);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.learn2develop.net/TicketingService/RegisterClient")]
        void RegisterClient(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.learn2develop.net/TicketingService/UnRegisterClient")]
        void UnRegisterClient(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TicketingServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.learn2develop.net/TicketingService/SeatStatus")]
        void SeatStatus(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TicketingServiceChannel : Client.ServiceReference1.TicketingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TicketingServiceClient : System.ServiceModel.DuplexClientBase<Client.ServiceReference1.TicketingService>, Client.ServiceReference1.TicketingService {
        
        public TicketingServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TicketingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TicketingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TicketingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TicketingServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SetSeatStatus(string strSeats) {
            base.Channel.SetSeatStatus(strSeats);
        }
        
        public void RegisterClient(System.Guid id) {
            base.Channel.RegisterClient(id);
        }
        
        public void UnRegisterClient(System.Guid id) {
            base.Channel.UnRegisterClient(id);
        }
    }
}
